#!/bin/bash

#	Choose audio folder
audiofolder='../whalesamples/*'

#	Iterate over the audio folder

for filename in $audiofolder
do
	new_filename="$(echo $filename | cut -f3 -d"." | cut -f3 -d"/" )"

	#sox $filename -n remix 1 lowpass 0.5k rate 4k spectrogram -X 1 -Y 1000 -r -O "../raw/"$new_filename"_1"
	#echo "../raw/"$new_filename"_1"
	#sox $filename -n remix 2 lowpass 0.5k rate 4k spectrogram -X 1 -Y 1000 -r -O "../raw/"$new_filename"_2"
	#echo "../raw/"$new_filename"_2"
	sox $filename -n remix 1,2 lowpass 0.5k rate 4k spectrogram -X 10 -Y 1000 -r -O "../raw/"$new_filename
	echo "../raw/"$new_filename
done


